#!/bin/sh
# shellcheck disable=SC2164
function drmi() {
  images=$(docker images -q -f dangling=true)
  if [[ -z "$images" ]]; then
     echo "No images to delete."
  else
    docker rmi -f $(printf " %s" "${images[@]}")
  fi
}
