cask_args appdir: '/Applications'

tap 'homebrew/bundle'

brew 'awscli'
brew 'coreutils'
brew 'git'
brew 'go'
brew 'n'
brew 'python'
brew 'ruby-build'
brew 'rbenv'
brew 'z'
brew 'zsh-syntax-highlighting'

# cask '1password'
# cask 'atom'
# cask 'firefox'
# cask 'google-chrome'
# cask 'handbrake'
# cask 'slack'
# cask 'steam'
# cask 'vlc'
