#!/bin/sh
# Setup a machine for Sublime Text 2
set -x

# symlink settings in
sublime_dir=~/Library/Application\ Support/Sublime\ Text\ 2/Packages
mv "$sublime_dir/User" "$sublime_dir/User.backup"
ln -s "$ZSH/sublime2/User" "$sublime_dir"

echo "Go install Package Manager, then install the following packges:"
echo "AdvancedNewFile"
echo "AndyJS2"
echo "ApacheConf.tmLanguage"
echo "Backbone.js"
echo "CoffeeScript"
echo "DocBlockr"
echo "Dotfiles Syntax Highlighting"
echo "EditorConfig"
echo "Emmet"
echo "jQuery"
echo "LESS"
echo "Package Control"
echo "SCSS"
echo "SideBarEnhancements"
echo "Solarized Color Scheme"
echo "SublimeLinter"
echo "Theme - Soda"
echo "Tomorrow Color Schemes"
echo "Underscore.js Snippets"
echo "Wordpress"
