#!/bin/sh
# Copy our color scheme over

# Check if directory exists, if not create it
if [ ! -d "~/Library/Developer/Xcode/UserData/FontAndColorThemes" ]; then
  mkdir "~/Library/Developer/Xcode/UserData/FontAndColorThemes"
fi

cp -R ~/Library/Developer/Xcode/UserData/FontAndColorThemes $ZSH/xcode/Jones.dvtcolortheme
