#!/bin/bash
# Credit for this general approach goes to https://github.com/fnichol/macosx-iterm2-settings
set -e

plist="com.googlecode.iterm2.plist"
new_plist="/tmp/$plist"
installed_plist="$HOME/Library/Preferences/$plist"
source_plist="$ZSH/iterm2/$plist.xml"

log()   { printf -- "-----> $*\n" ; return $? ; }
warn()  { printf -- ">>>>>> $*\n" ; return $? ; }

if [[ "$TERM_PROGRAM" == "iTerm.app" ]] ; then
  warn "You appear to be running this script from within iTerm.app which could"
  warn "overwrite your new preferences on quit.\n"
  warn "Please quit iTerm and run this from Terminal.app or an SSH session.\n"
  exit 2
fi

if ps wwwaux | egrep -q 'iTerm\.app' >/dev/null ; then
  warn "You appear to have iTerm.app currently running. Please quit the"
  warn "application so your updates won't get overridden on quit.\n"
  exit 3
fi

log "Converting source xml plist to binary"
plutil -convert binary1 -r -o $new_plist $source_plist

if [[ $? -eq 0 ]] ; then
  cp -f "$new_plist" "$installed_plist" && rm -f $new_plist
  log "iTerm preferences installed/updated in $installed_plist."
else
  warn "The conversion from XML to binary failed. Your current"
  warn "preferences have not been changed.\n"
  exit 4
fi

exit $?
